# Generated by Django 5.2 on 2025-04-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generaator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedname',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
